    _                _                      
   / \   ___ ___ ___| | ___ _ __ __ _ _   _ 
  / _ \ / __/ __/ _ \ |/ _ \ '__/ _` | | | |
 / ___ \ (_| (_|  __/ |  __/ | | (_| | |_| |
/_/   \_\___\___\___|_|\___|_|  \__, |\__, |
                                |___/ |___/ 

Info: generating outputs according to the following specified output flags... 
 Please use the -f flag to update the preference (default to all output files) 
{'ERT': 1, 'ERT_summary': 1, 'ART': 1, 'ART_summary': 1, 'energy_estimation': 1, 'flattened_arch': 1}
Info: config file located: /home/workspace/.config/accelergy/accelergy_config.yaml 
config file content: 
 {'version': 0.3, 'compound_components': [], 'estimator_plug_ins': ['/usr/local/share/accelergy/estimation_plug_ins'], 'primitive_components': ['/usr/local/share/accelergy/primitive_component_libs'], 'table_plug_ins': {'roots': ['/usr/local/share/accelergy/estimation_plug_ins/accelergy-table-based-plug-ins/set_of_table_templates']}}
Warn: Cannot recognize the top key "mapper" in file /home/workspace/workspace/final-project/timeloop_results/eyeriss_like_672pe/mapper/mapper.yaml 
Warn: Cannot recognize the top key "architecture_constraints" in file /home/workspace/workspace/final-project/timeloop_results/eyeriss_like_672pe/constraints/eyeriss_like_arch_constraints.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/accelergy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelergy/accelergy_console.py", line 164, in main
    run()
  File "/usr/local/lib/python3.8/dist-packages/accelergy/accelergy_console.py", line 73, in run
    raw_dicts = RawInputs2Dicts(raw_input_info)
  File "/usr/local/lib/python3.8/dist-packages/accelergy/raw_inputs_2_dicts.py", line 21, in __init__
    self.load_and_construct_dicts()
  File "/usr/local/lib/python3.8/dist-packages/accelergy/raw_inputs_2_dicts.py", line 69, in load_and_construct_dicts
    loaded_content_list = self.load_file(path)
  File "/usr/local/lib/python3.8/dist-packages/accelergy/raw_inputs_2_dicts.py", line 115, in load_file
    file_obj = open(file_path)
  File "/usr/lib/python3.8/_bootlocale.py", line 33, in getpreferredencoding
    def getpreferredencoding(do_setlocale=True):
KeyboardInterrupt
